### ISSUE TITLE
Question about hugetlbfs test

### ISSUE THREAD

**Issue by gautammenghani** [awslabs/damon-tests#1]
Hi @sjp38 ,

I have a question about the hugetlbfs test. The TODO in corr/TODO says "Test hugetlbfs". I want to understand what is required in this.
Do we need a test that writes data to hugepages and reads it back to check if read/write is successful?
Or do we need a hugepage scheme that is applied on masim, which we then check to ensure hugepages were used?
Or is something else required?
Please advise on this.

Thanks.

**Comment by sj-aws** [comment]
Sorry for late response.  I've answered to your same question on DAMON mailing list: https://lore.kernel.org/damon/20220816205030.96988-1-sj@kernel.org/

If that doesn't answer your question, please open this ticket again.
